export const fontelloIconSet = [
  'awethentique-mail',
  'awethentique-desktop',
  'awethentique-terminal',
  'awethentique-cloud',
  'awethentique-laptop',
  'awethentique-tablet',
  'awethentique-mobile',
  'awethentique-wifi',
  'awethentique-monitor',
  'awethentique-mobile-1',
  'awethentique-user',
  'awethentique-rss',
  'awethentique-cog',
  'awethentique-spin1',
  'awethentique-spin2',
  'awethentique-spin3',
  'awethentique-spin4',
  'awethentique-spin5',
  'awethentique-spin6',
  'awethentique-firefox',
  'awethentique-chrome',
  'awethentique-opera',
  'awethentique-ie',
  'awethentique-crown',
  'awethentique-google',
  'awethentique-linkedin-rect',
  'awethentique-youtube',
] as const;

export default { fontelloIconSet };
